"use client";
import { useState } from "react";
const examples = [
  { url: "stripe.com", title: "Stripe: Financial infrastructure for the internet", type: "Website", tone: "purple" },
  { url: "vercel.com", title: "Vercel: Build and deploy the best web experiences", type: "Website", tone: "blue" },
  { url: "github.com", title: "GitHub · Change is constant. GitHub keeps you ahead.", type: "Website", tone: "orange" }
];
function normalizeUrl(value: string) { return /^https?:\/\//i.test(value) ? value : "https://" + value; }
export default function Home() {
  const [url, setUrl] = useState(""); const [loading, setLoading] = useState(false); const [result, setResult] = useState<any>(null); const [active, setActive] = useState("Inspect");
  async function inspect(value = url) {
    if (!value.trim()) return; setUrl(value); setLoading(true); setResult(null);
    try { const response = await fetch("/api/inspect?url=" + encodeURIComponent(normalizeUrl(value))); const data = await response.json(); if (response.ok) setResult({ url: data.url, title: data.title || "Untitled page", type: data.contentType?.split(";")[0] || "Website", tone: "purple" }); else setResult({ url: normalizeUrl(value), title: "Ready to inspect", type: "Payment required · 0.01 USDC", tone: "purple" }); } catch { setResult({ url: normalizeUrl(value), title: "Ready to inspect", type: "Payment required · 0.01 USDC", tone: "purple" }); } setLoading(false);
  }
  return <main>
    <aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>link lens</span></div><div className="workspace"><span className="avatar">L</span><span>Link Lens</span><span className="chevron">⌄</span></div><nav>{["Inspect", "History", "API docs"].map(item => <button key={item} className={"nav-item " + (active === item ? "selected" : "")} onClick={() => setActive(item)}><span className="nav-icon">{item === "Inspect" ? "⌕" : item === "History" ? "◷" : "⌘"}</span>{item}</button>)}</nav><div className="side-bottom"><div className="usage"><div className="usage-top"><span>Monthly usage</span><span>12 / 100</span></div><div className="progress"><i /></div><small>Resets in 18 days</small></div><button className="help">? <span>Help center</span></button><div className="profile"><span className="avatar dark">JD</span><span><b>Jordan Davis</b><small>jordan@linklens.dev</small></span><span className="dots">•••</span></div></div></aside>
    <section className="content"><header><div><p className="eyebrow">URL INTELLIGENCE</p><h1>Inspect a link</h1><p className="subhead">Turn any public URL into structured, useful data.</p></div><div className="header-actions"><span className="status-dot" /> API operational <button className="docs-btn" onClick={() => setActive("API docs")}>View docs <span>↗</span></button></div></header>
      {active === "API docs" ? <Docs /> : <><div className="hero-card"><div className="orb orb-one" /><div className="orb orb-two" /><div className="hero-copy"><span className="sparkle">✦</span><h2>See what’s behind<br />every link.</h2><p>Get metadata, readable text, and more from any webpage<br />in one simple API call.</p></div><div className="mini-preview"><div className="mini-top"><span className="tiny-logo">✦</span><span>linklens.dev</span><span className="green">● live</span></div><div className="mini-line wide" /><div className="mini-line" /><div className="mini-tags"><span>title</span><span>description</span><span>links</span></div></div></div>
      <div className="inspect-box"><div className="input-wrap"><span className="link-icon">↗</span><input value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === "Enter" && inspect()} placeholder="Paste a URL to inspect..." /><kbd>⌘ ↵</kbd></div><button className="inspect-btn" onClick={() => inspect()} disabled={loading}>{loading ? "Inspecting..." : "Inspect link"}<span>→</span></button></div>
      <div className="section-heading"><div><h3>{result ? "Inspection result" : "Recent inspections"}</h3><p>{result ? "Structured data from your URL" : "Your latest links, at a glance."}</p></div>{!result && <button className="filter">All time⌄</button>}</div>
      {result ? <div className="result-card"><div className={"site-icon " + result.tone}>✦</div><div className="result-main"><b>{result.title}</b><span>{result.url}</span>{result.type.startsWith("Payment required") && <a href={"/api/inspect?url=" + encodeURIComponent(result.url)} target="_blank" rel="noreferrer" style={{ display: "inline-block", marginTop: 14, background: "#6c56d5", color: "#fff", borderRadius: 6, padding: "8px 11px", fontSize: 11, fontWeight: 600 }}>Pay now · 0.01 USDC →</a>}</div><div className="result-meta"><span>{result.type}</span><strong>JSON ↗</strong></div></div> : <div className="cards">{examples.map(item => <button className="link-card" key={item.url} onClick={() => inspect(item.url)}><div className={"site-icon " + item.tone}>{item.url[0].toUpperCase()}</div><div className="card-copy"><b>{item.url}</b><span>{item.title}</span><small>Just now <i>·</i> 0.01 USDC</small></div><span className="arrow">↗</span></button>)}</div>}
      <div className="hint"><span>✦</span><p><b>Built for agents.</b> Link Lens is x402-native, so every request is pay-per-use. No accounts, no API keys.</p><a href="#api">Learn about x402 →</a></div></>}</section>
  </main>;
}
function Docs() { return <div className="docs-panel"><div className="docs-copy"><span className="pill">GET</span><h2>Inspect any public URL.</h2><p>One endpoint for clean metadata and readable content, priced per request.</p><div className="endpoint">https://linklens.dev/api/inspect?url=https://example.com <span>▣</span></div><div className="doc-stats"><div><b>0.01</b><span>USDC / request</span></div><div><b>JSON</b><span>response format</span></div><div><b>8453</b><span>Base mainnet</span></div></div></div><div className="code"><div className="code-head"><span>Request</span><span>Response</span></div><pre>{"curl -X GET \\\n  'https://linklens.dev/api/inspect?url=https://example.com' \\\n  -H 'x-payment: <payment-header>'"}</pre><div className="code-foot">x402 payment required <span>→</span></div></div></div> }
